"""fix city/favorite relationships

Revision ID: b399c374ce4b
Revises: 905d4d6b2cb0
Create Date: 2024-11-29 18:44:13.384725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b399c374ce4b'
down_revision = '905d4d6b2cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index('ix_favorites_city_id')
        batch_op.create_index(batch_op.f('ix_favorites_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_user_id'))
        batch_op.create_index('ix_favorites_city_id', ['city_id'], unique=False)

    # ### end Alembic commands ###
